(load (merge-pathnames "../src/package.lisp" *load-truename*))
(load (merge-pathnames "../src/core.lisp" *load-truename*))
(load (merge-pathnames "../src/worlds.lisp" *load-truename*))
(load (merge-pathnames "../src/rules.lisp" *load-truename*))
(load (merge-pathnames "../src/inspect.lisp" *load-truename*))
(load (merge-pathnames "../src/graph.lisp" *load-truename*))
(load (merge-pathnames "../src/viewer.lisp" *load-truename*))
(load (merge-pathnames "../src/browser.lisp" *load-truename*))

(in-package #:cl-user)

(defvar *failures* 0)

(defmacro check (form)
  `(unless ,form
     (incf *failures*)
     (format t "~&FAIL: ~S~%" ',form)))

(defun names (units)
  (mapcar #'kee:unit.name units))

(defun quit-with-status (status)
  #+sbcl (sb-ext:exit :code status)
  #-sbcl (error "Tests failed with status ~D." status))

(defun signals-error-p (thunk)
  (handler-case
      (progn (funcall thunk) nil)
    (error () t)))

(defun run ()
  (kee:reset-kee)
  (kee:create.kb 'veg)
  (kee:create.unit 'classes 'veg nil nil)
  (kee:create.unit 'entities 'veg nil nil)
  (kee:create.unit 'target.data 'veg 'entities 'classes)
  (kee:create.slot 'target.data 'source 'member '(manual))
  (kee:create.unit 'estimate.hemispherical.reflectance 'veg 'entities nil)
  (let ((sample (kee:create.unit 'sample.1 'veg nil '(target.data))))
    (check (eq (kee:get.value sample 'source) 'manual))
    (kee:put.value sample 'source 'manual)
    (kee:put.value sample 'complete.description "demo sample")
    (check (string= (kee:get.value sample 'complete.description)
                    "demo sample"))
    (kee:add.value 'estimate.hemispherical.reflectance 'new.samples sample)
    (check (equal (names (kee:get.values 'estimate.hemispherical.reflectance
                                        'new.samples))
                  '(sample.1)))
    (check (equal (names (kee:unit.parents sample 'member))
                  '(target.data)))
    (check (member 'sample.1 (names (kee:unit.children 'target.data 'member))))
    (kee:put.value 'target.data 'source 'file)
    (check (eq (kee:get.value sample 'source) 'manual))
    (kee:remove.all.values sample 'source)
    (check (eq (kee:get.value sample 'source) 'file)))
  (kee:create.unit 'worker 'veg 'entities nil)
  (kee:put.value 'worker 'initialize.system
                 (lambda (self)
                   (kee:put.value self 'state 'initialized)))
  (kee:unitmsg 'worker 'initialize.system)
  (check (eq (kee:get.value 'worker 'state) 'initialized))
  (let ((log nil))
    (kee:create.unit 'drawable 'veg 'entities 'classes)
    (kee:create.slot 'drawable 'draw 'member nil 'method 'method)
    (kee:add.method 'drawable 'draw :before
                    (lambda (self)
                      (declare (ignore self))
                      (push 'parent-before log)))
    (kee:add.method 'drawable 'draw :primary
                    (lambda (self)
                      (declare (ignore self))
                      (push 'parent-primary log)))
    (kee:add.method 'drawable 'draw :after
                    (lambda (self)
                      (declare (ignore self))
                      (push 'parent-after log)))
    (kee:create.unit 'highlighted.drawable 'veg 'drawable nil)
    (kee:add.method 'highlighted.drawable 'draw :before
                    (lambda (self)
                      (declare (ignore self))
                      (push 'child-before log)))
    (kee:add.method 'highlighted.drawable 'draw :after
                    (lambda (self)
                      (declare (ignore self))
                      (push 'child-after log)))
    (kee:unitmsg 'highlighted.drawable 'draw)
    (check (equal (reverse log)
                  '(child-before parent-before parent-primary
                    child-after parent-after)))
    (setf log nil)
    (kee:add.method 'highlighted.drawable 'draw :primary
                    (lambda (self)
                      (declare (ignore self))
                      (push 'child-primary log)))
    (kee:unitmsg 'highlighted.drawable 'draw)
    (check (equal (reverse log)
                  '(child-before parent-before child-primary
                    child-after parent-after))))
  (let ((events nil))
    (kee:create.unit 'audit.av 'veg 'entities nil)
    (kee:put.value 'audit.av 'kee:value-written
                   (lambda (self target slot old new)
                     (declare (ignore self))
                     (push (list 'written (kee:unit.name target) slot old new)
                           events)))
    (kee:put.value 'audit.av 'kee:value-read
                   (lambda (self target slot old new)
                     (declare (ignore self old))
                     (push (list 'read (kee:unit.name target) slot new)
                           events)))
    (kee:put.facet.value 'sample.1 'complete.description
                         'kee:active.values 'audit.av)
    (kee:put.value 'sample.1 'complete.description "changed")
    (kee:get.value 'sample.1 'complete.description)
    (check (equal (reverse events)
                  '((written sample.1 complete.description
                     ("demo sample") ("changed"))
                    (read sample.1 complete.description ("changed"))))))
  (kee:create.unit 'technique.selection.rules 'veg 'entities 'classes)
  (kee:put.value 'technique.selection.rules 'kee:parse #'kee:parse)
  (let ((wave (kee:create.unit 'wavelength.1 'veg nil nil)))
    (kee:add.value 'estimate.hemispherical.reflectance
                   'current.sample.wavelengths
                   wave)
    (kee:put.value wave 'reflectance.data '((0 0 0.31) (30 180 0.28)))
    (kee:create.unit 'pgcswr.10 'veg nil 'technique.selection.rules)
    (kee:put.value 'pgcswr.10 'kee:external.form
                   '(if (the current.sample.wavelengths
                         of estimate.hemispherical.reflectance
                         is ?x)
                        (lisp (consp (get.value ?x 'reflectance.data)))
                        then
                        (lisp (add.value ?x 'techniques
                                         'pgc.near.nadir))))
    (kee:create.unit 'pgc.followup 'veg nil 'technique.selection.rules)
    (kee:put.value 'pgc.followup 'kee:external.form
                   '(if (the current.sample.wavelengths
                         of estimate.hemispherical.reflectance
                         is ?x)
                        (the techniques of ?x is pgc.near.nadir)
                        then
                        (lisp (add.value ?x 'recommended.techniques
                                         'pgc.near.nadir))))
    (check (kee:unitmsg 'pgcswr.10 'kee:parse))
    (check (kee:unitmsg 'pgc.followup 'kee:parse))
    (check (null (kee:get.value 'pgcswr.10 'kee:parse.errors)))
    (check (equal (sort (names (kee:forward.chain 'technique.selection.rules))
                        #'string<
                        :key #'symbol-name)
                  '(pgc.followup pgcswr.10)))
    (check (equal (kee:get.values wave 'techniques)
                  '(pgc.near.nadir)))
    (check (equal (kee:get.values wave 'recommended.techniques)
                  '(pgc.near.nadir)))
    (kee:forward.chain 'technique.selection.rules)
    (check (equal (kee:get.values wave 'techniques)
                  '(pgc.near.nadir)))
    (check (equal (kee:get.values wave 'recommended.techniques)
                  '(pgc.near.nadir))))
  (kee:create.unit 'people 'veg 'entities 'classes)
  (kee:create.slot 'people 'sport 'member nil nil nil nil
                   '((kee:value.class (kee:one.of golf basketball sailing))
                     (kee:min.cardinality 1)
                     (kee:max.cardinality 1)))
  (kee:create.slot 'people 'phobia 'member nil nil nil nil
                   '((kee:value.class (kee:one.of cats heights close.spaces))
                     (kee:min.cardinality 1)
                     (kee:max.cardinality 1)))
  (kee:create.unit 'tom 'veg nil 'people)
  (check (equal (kee:slot.facet.values 'tom 'sport 'kee:value.class)
                '((kee:one.of golf basketball sailing))))
  (check (signals-error-p
          (lambda ()
            (kee:put.value 'tom 'sport 'tennis))))
  (kee:create.unit 'constraint.rules 'veg 'entities 'classes)
  (check (equal (kee:list.kbs) '(veg)))
  (check (member 'tom (names (kee:list.units 'veg))))
  (let ((tom-report (kee:inspect.unit 'tom))
        (sport-report (kee:inspect.slot 'tom 'sport))
        (browser-text (with-output-to-string (stream)
                        (kee:print.browser :stream stream
                                           :units '(tom)
                                           :worlds nil))))
    (check (eq (getf tom-report :name) 'tom))
    (check (member 'people (getf tom-report :member-parents)))
    (check (equal (getf sport-report :facets)
                  '((kee:max.cardinality 1)
                    (kee:min.cardinality 1)
                    (kee:value.class
                     (kee:one.of golf basketball sailing)))))
    (check (search "TOM" browser-text))
    (check (search "SPORT" browser-text)))
  (let ((command-text
          (with-output-to-string (stream)
            (check (eq (kee:browser.command '(help) :stream stream)
                       :continue))
            (check (eq (kee:browser.command '(kbs) :stream stream)
                       :continue))
            (check (eq (kee:browser.command '(units veg) :stream stream)
                       :continue))
            (check (eq (kee:browser.command '(unit tom) :stream stream)
                       :continue))
            (check (eq (kee:browser.command '(slot tom sport) :stream stream)
                       :continue))
            (check (eq (kee:browser.command '(unit-graph veg) :stream stream)
                       :continue))
            (check (eq (kee:browser.command '(viewer 2) :stream stream)
                       :continue))
            (check (eq (kee:browser.command '(current) :stream stream)
                       :continue))
            (check (eq (kee:browser.command '(quit) :stream stream)
                       :quit)))))
    (check (search "Commands:" command-text))
    (check (search "Knowledge Bases" command-text))
    (check (search "Units in VEG" command-text))
    (check (search "TOM" command-text))
    (check (search "SPORT" command-text))
    (check (search "digraph" command-text))
    (check (search "<!doctype html>" command-text))
    (check (search "member" command-text))
    (check (search "Leaving KEE browser" command-text)))
  (let* ((unit-graph (kee:unit.graph :kb 'veg))
         (unit-dot (kee:unit.graph.dot :kb 'veg))
         (viewer-html (kee:kee.viewer.html :kb 'veg :world-limit 0)))
    (check (member "unit:VEG/TOM" (getf unit-graph :nodes)
                   :test #'string=
                   :key (lambda (node) (getf node :id))))
    (check (member 'member (getf unit-graph :edges)
                   :key (lambda (edge) (getf edge :relation))))
    (check (search "digraph" unit-dot))
    (check (search "unit:VEG/TOM" unit-dot))
    (check (search "id='kee-data'" viewer-html))
    (check (search "unit:VEG/TOM" viewer-html))
    (check (search "function render" viewer-html)))
  (let ((loop-text
          (with-output-to-string (output)
            (with-input-from-string (input "(kbs) (quit)")
              (check (eq (kee:browse :input input :output output)
                         :quit))))))
    (check (search "KEE browser" loop-text))
    (check (search "Knowledge Bases" loop-text)))
  (kee:create.unit 'heights.golf 'veg nil 'constraint.rules)
  (kee:put.value 'heights.golf 'kee:external.form
                 '(while (the sport of ?person is golf)
                         (the phobia of ?person is heights)
                    believe false))
  (check (kee:parse 'heights.golf))
  (let ((bad-world (kee:create.world 'tom-golf-heights))
        (good-world (kee:create.world 'tom-golf-cats)))
    (kee:with-world (bad-world)
      (kee:put.value 'tom 'sport 'golf)
      (kee:put.value 'tom 'phobia 'heights)
      (kee:forward.chain 'constraint.rules)
      (check (kee:world.inconsistent.p bad-world))
      (let ((reasons (kee:why.false bad-world)))
        (check (= (length reasons) 1))
        (check (eq (kee:justification.rule (first reasons)) 'heights.golf))
        (check (equal (cdr (assoc "?PERSON"
                                  (kee:justification.bindings (first reasons))
                                  :test #'string=))
                      'tom))
        (check (equal (kee:justification.proposition (first reasons))
                      'false))))
    (kee:with-world (good-world)
      (kee:put.value 'tom 'sport 'golf)
      (kee:put.value 'tom 'phobia 'cats)
      (kee:forward.chain 'constraint.rules)
      (check (not (kee:world.inconsistent.p good-world))))
    (let ((bad-report (kee:inspect.world bad-world))
          (browser-text (with-output-to-string (stream)
                          (kee:print.browser :stream stream
                                             :units '(tom)
                                             :worlds (kee:inspect.world.tree)))))
      (check (eq (getf bad-report :name) 'tom-golf-heights))
      (check (getf bad-report :inconsistent-p))
      (check (= (length (getf bad-report :nogoods)) 1))
      (check (search "TOM-GOLF-HEIGHTS" browser-text))
      (check (search "HEIGHTS.GOLF" browser-text)))
    (let* ((world-graph (kee:world.graph))
           (world-dot (kee:world.graph.dot)))
      (check (member "world:TOM-GOLF-HEIGHTS" (getf world-graph :nodes)
                     :test #'string=
                     :key (lambda (node) (getf node :id))))
      (check (search "mistyrose" world-dot))
      (check (search "TOM-GOLF-HEIGHTS" world-dot)))
    (check (kee:true.in.world bad-world 'tom 'sport 'golf))
    (check (null (kee:get.value 'tom 'sport))))
  (kee:create.unit 'hypothesis.rules 'veg 'entities 'classes)
  (kee:create.unit 'guess.tom.golf 'veg nil 'hypothesis.rules)
  (kee:put.value 'guess.tom.golf 'kee:external.form
                 '(if (the needs.guess of ?person is sport)
                      (lisp (cant.find ?person 'sport))
                      then
                      (in.new.world
                       (the sport of ?person is values))))
  (check (kee:parse 'guess.tom.golf))
  (let ((root-world (kee:create.world 'root-hypotheses)))
    (kee:with-world (root-world)
      (kee:put.value 'tom 'needs.guess 'sport)
      (kee:forward.chain 'hypothesis.rules)
      (kee:forward.chain 'hypothesis.rules))
    (let ((children (remove-if-not
                     (lambda (world)
                       (eq (kee:world.parent world) root-world))
                     (kee:$worlds))))
      (check (= (length children) 3))
      (check (equal (sort (mapcar (lambda (child)
                                     (kee:with-world (child)
                                       (first (kee:get.values 'tom 'sport))))
                                   children)
                          #'string<
                          :key #'symbol-name)
                    '(basketball golf sailing)))
      (let ((child (find-if (lambda (world)
                              (kee:true.in.world world 'tom 'sport 'golf))
                            children)))
        (check child)
        (check (not (kee:true.in.world root-world 'tom 'sport 'golf)))
        (check (member 'sport (kee:world.facts child)
                       :key (lambda (fact) (getf fact :slot)))))))
  (format t "~&~A~%" (if (zerop *failures*) "All tests passed." "Tests failed."))
  (unless (zerop *failures*)
    (quit-with-status 1)))

(run)
