(load (merge-pathnames "../src/package.lisp" *load-truename*))
(load (merge-pathnames "../src/core.lisp" *load-truename*))
(load (merge-pathnames "../src/active-images.lisp" *load-truename*))
(load (merge-pathnames "../src/traces.lisp" *load-truename*))
(load (merge-pathnames "../src/pictures.lisp" *load-truename*))
(load (merge-pathnames "../src/panels.lisp" *load-truename*))
(load (merge-pathnames "../src/dump.lisp" *load-truename*))
(load (merge-pathnames "../src/worlds.lisp" *load-truename*))
(load (merge-pathnames "../src/rules.lisp" *load-truename*))
(load (merge-pathnames "../src/inspect.lisp" *load-truename*))
(load (merge-pathnames "../src/graph.lisp" *load-truename*))
(load (merge-pathnames "../src/viewer.lisp" *load-truename*))
(load (merge-pathnames "../src/browser.lisp" *load-truename*))

(in-package #:cl-user)

(defvar *failures* 0)

(defmacro check (form)
  `(unless ,form
     (incf *failures*)
     (format t "~&FAIL: ~S~%" ',form)))

(defun names (units)
  (mapcar #'kee:unit.name units))

(defun quit-with-status (status)
  #+sbcl (sb-ext:exit :code status)
  #-sbcl (error "Tests failed with status ~D." status))

(defun signals-error-p (thunk)
  (handler-case
      (progn (funcall thunk) nil)
    (error () t)))

(defun run ()
  (kee:reset-kee)
  (check (null (kee:trace.events)))
  (kee:create.kb 'veg)
  (kee:create.unit 'classes 'veg nil nil)
  (kee:create.unit 'entities 'veg nil nil)
  (kee:create.unit 'target.data 'veg 'entities 'classes)
  (kee:create.slot 'target.data 'source 'member '(manual))
  (kee:create.unit 'estimate.hemispherical.reflectance 'veg 'entities nil)
  (let ((sample (kee:create.unit 'sample.1 'veg nil '(target.data))))
    (check (eq (kee:get.value sample 'source) 'manual))
    (kee:put.value sample 'source 'manual)
    (kee:put.value sample 'complete.description "demo sample")
    (check (string= (kee:get.value sample 'complete.description)
                    "demo sample"))
    (kee:add.value 'estimate.hemispherical.reflectance 'new.samples sample)
    (check (equal (names (kee:get.values 'estimate.hemispherical.reflectance
                                        'new.samples))
                  '(sample.1)))
    (check (equal (names (kee:unit.parents sample 'member))
                  '(target.data)))
    (check (member 'sample.1 (names (kee:unit.children 'target.data 'member))))
    (kee:put.value 'target.data 'source 'file)
    (check (eq (kee:get.value sample 'source) 'manual))
    (kee:remove.all.values sample 'source)
    (check (eq (kee:get.value sample 'source) 'file)))
  (kee:create.unit 'worker 'veg 'entities nil)
  (kee:put.value 'worker 'initialize.system
                 (lambda (self)
                   (kee:put.value self 'state 'initialized)))
  (kee:unitmsg 'worker 'initialize.system)
  (check (eq (kee:get.value 'worker 'state) 'initialized))
  (let ((log nil))
    (kee:create.unit 'drawable 'veg 'entities 'classes)
    (kee:create.slot 'drawable 'draw 'member nil 'method 'method)
    (kee:add.method 'drawable 'draw :before
                    (lambda (self)
                      (declare (ignore self))
                      (push 'parent-before log)))
    (kee:add.method 'drawable 'draw :primary
                    (lambda (self)
                      (declare (ignore self))
                      (push 'parent-primary log)))
    (kee:add.method 'drawable 'draw :after
                    (lambda (self)
                      (declare (ignore self))
                      (push 'parent-after log)))
    (kee:create.unit 'highlighted.drawable 'veg 'drawable nil)
    (kee:add.method 'highlighted.drawable 'draw :before
                    (lambda (self)
                      (declare (ignore self))
                      (push 'child-before log)))
    (kee:add.method 'highlighted.drawable 'draw :after
                    (lambda (self)
                      (declare (ignore self))
                      (push 'child-after log)))
    (kee:unitmsg 'highlighted.drawable 'draw)
    (check (equal (reverse log)
                  '(child-before parent-before parent-primary
                    child-after parent-after)))
    (check (find-if
            (lambda (event)
              (and (eq (getf event :kind) :method-call)
                   (eq (getf event :unit) 'highlighted.drawable)
                   (eq (getf event :slot) 'draw)
                   (eq (getf event :method-kind) :primary)))
            (kee:trace.events :kind :method-call)))
    (setf log nil)
    (kee:add.method 'highlighted.drawable 'draw :primary
                    (lambda (self)
                      (declare (ignore self))
                      (push 'child-primary log)))
    (kee:unitmsg 'highlighted.drawable 'draw)
    (check (equal (reverse log)
                  '(child-before parent-before child-primary
                    child-after parent-after))))
  (let ((events nil))
    (kee:create.unit 'audit.av 'veg 'entities nil)
    (kee:put.value 'audit.av 'kee:value-written
                   (lambda (self target slot old new)
                     (declare (ignore self))
                     (push (list 'written (kee:unit.name target) slot old new)
                           events)))
    (kee:put.value 'audit.av 'kee:value-read
                   (lambda (self target slot old new)
                     (declare (ignore self old))
                     (push (list 'read (kee:unit.name target) slot new)
                           events)))
    (kee:put.facet.value 'sample.1 'complete.description
                         'kee:active.values 'audit.av)
    (kee:put.value 'sample.1 'complete.description "changed")
    (kee:get.value 'sample.1 'complete.description)
    (check (equal (reverse events)
                  '((written sample.1 complete.description
                     ("demo sample") ("changed"))
                    (read sample.1 complete.description ("changed"))))))
  (let ((events nil))
    (kee:create.unit 'meter.av 'veg 'entities nil)
    (kee:put.value 'meter.av 'kee:value-written
                   (lambda (self target slot old new)
                     (declare (ignore self))
                     (push (list 'meter-write (kee:unit.name target)
                                 slot old new)
                           events)))
    (kee:create.unit 'sensor.1 'veg nil '(target.data))
    (kee:create.slot 'sensor.1 'temperature 'member '(21)
                     nil nil nil '((kee:active.values meter.av)))
    (kee:create.active.image 'temperature.gauge 'sensor.1 'temperature
                             :widget :gauge
                             :label "Temperature"
                             :min 0
                             :max 100
                             :writable-p t)
    (check (equal (names (kee:list.active.images 'veg))
                  '(temperature.gauge)))
    (check (eql (kee:active.image.value 'temperature.gauge) 21))
    (let ((report (kee:active.image.report 'temperature.gauge))
          (html (kee:active.image.html 'temperature.gauge)))
      (check (eq (getf report :target-unit) 'sensor.1))
      (check (eq (getf report :target-slot) 'temperature))
      (check (eq (getf report :widget) :gauge))
      (check (getf report :writable-p))
      (check (search "active-image-gauge" html))
      (check (search "Temperature" html))
      (check (search "data-target-slot='TEMPERATURE'" html)))
    (kee:set.active.image.value 'temperature.gauge 42)
    (check (eql (kee:get.value 'sensor.1 'temperature) 42))
    (check (equal (reverse events)
                  '((meter-write sensor.1 temperature (21) (42)))))
    (kee:create.kee.picture 'sensor.panel
                            :width 240
                            :height 120
                            :label "Sensor Panel")
    (kee:create.picture.item 'sensor.panel 'panel.frame :rectangle
                             :x 8
                             :y 8
                             :width 224
                             :height 104
                             :fill "#FFFFFF")
    (kee:create.picture.item 'sensor.panel 'panel.title :text
                             :x 18
                             :y 28
                             :text "KEEpicture sensor panel")
    (kee:create.picture.item 'sensor.panel 'temperature.card :active-image
                             :active-image 'temperature.gauge
                             :x 18
                             :y 40
                             :width 150
                             :height 58)
    (kee:create.picture.item 'sensor.panel 'temperature.value :value
                             :target-unit 'sensor.1
                             :target-slot 'temperature
                             :label "Slot value"
                             :x 18
                             :y 108)
    (kee:create.picture.viewport 'sensor.viewport 'sensor.panel
                                 :label "Sensor View"
                                 :width 240
                                 :height 120)
    (kee:create.picture.windowpane 'sensor.window 'sensor.viewport
                                   :label "Sensor Window"
                                   :width 260
                                   :height 150
                                   :open-p nil)
    (kee:create.kee.panel 'sensor.image.panel
                          :kind :status
                          :label "Sensor Image Panel"
                          :message "Mouse edits update the sensor"
                          :picture 'sensor.panel
                          :viewport 'sensor.viewport
                          :windowpane 'sensor.window
                          :open-p nil)
    (check (equal (names (kee:list.kee.pictures 'veg))
                  '(sensor.panel)))
    (check (equal (names (kee:picture.items 'sensor.panel))
                  '(panel.frame panel.title temperature.card
                    temperature.value)))
    (check (equal (names (kee:picture.viewports 'sensor.panel))
                  '(sensor.viewport)))
    (check (equal (names (kee:picture.windowpanes 'sensor.viewport))
                  '(sensor.window)))
    (check (equal (names (kee:list.kee.panels 'veg))
                  '(sensor.image.panel)))
    (let ((panel-report (kee:kee.panel.report 'sensor.image.panel)))
      (check (eq (getf panel-report :name) 'sensor.image.panel))
      (check (eq (getf panel-report :kind) :status))
      (check (eq (getf panel-report :picture) 'sensor.panel))
      (check (eq (getf panel-report :viewport) 'sensor.viewport))
      (check (eq (getf panel-report :windowpane) 'sensor.window))
      (check (not (getf panel-report :open-p)))
      (check (search "class='kee-picture'" (getf panel-report :svg))))
    (kee:open.panel 'sensor.image.panel)
    (check (kee:panel.open.p 'sensor.image.panel))
    (check (kee:get.value 'sensor.window 'kee::open.p))
    (kee:unitmsg 'sensor.image.panel 'kee:close-panel!)
    (check (not (kee:panel.open.p 'sensor.image.panel)))
    (check (not (kee:get.value 'sensor.window 'kee::open.p)))
    (kee:unitmsg 'sensor.image.panel 'kee:open!)
    (check (kee:panel.open.p 'sensor.image.panel))
    (let ((event (first (last (kee:trace.events :kind :panel-open)))))
      (check (eq (getf event :panel) 'sensor.image.panel))
      (check (eq (getf event :picture) 'sensor.panel))
      (check (eq (getf event :viewport) 'sensor.viewport))
      (check (eq (getf event :windowpane) 'sensor.window))
      (check (eq (getf event :action) 'kee:open!)))
    (let ((report (kee:kee.picture.report 'sensor.panel))
          (svg (kee:kee.picture.svg 'sensor.panel)))
      (check (eq (getf report :name) 'sensor.panel))
      (check (= (length (getf report :items)) 4))
      (check (= (length (getf report :viewports)) 1))
      (check (search "class='kee-picture'" svg))
      (check (search "KEEpicture sensor panel" svg))
      (check (search "data-picture-item='TEMPERATURE.CARD'" svg))
      (check (search "Temperature" svg))
      (check (search "42" svg)))
    (kee:picture.mouse.event 'sensor.panel 'temperature.card :mouse-left
                             :viewport 'sensor.viewport
                             :windowpane 'sensor.window
                             :x 82
                             :y 68
                             :button :left
                             :value 55)
    (check (eql (kee:get.value 'sensor.1 'temperature) 55))
    (check (search "55" (kee:kee.picture.svg 'sensor.panel)))
    (let ((event (first (last (kee:trace.events :kind :picture-mouse)))))
      (check (eq (getf event :picture) 'sensor.panel))
      (check (eq (getf event :item) 'temperature.card))
      (check (eq (getf event :viewport) 'sensor.viewport))
      (check (eq (getf event :windowpane) 'sensor.window))
      (check (eq (getf event :action) :mouse-left))
      (check (equal (getf event :old-values) '(42)))
      (check (equal (getf event :new-values) '(55)))
      (check (eq (getf event :result) :active-image-write))))
  (kee:create.unit 'technique.selection.rules 'veg 'entities 'classes)
  (kee:put.value 'technique.selection.rules 'kee:parse #'kee:parse)
  (let ((wave (kee:create.unit 'wavelength.1 'veg nil nil)))
    (kee:add.value 'estimate.hemispherical.reflectance
                   'current.sample.wavelengths
                   wave)
    (kee:put.value wave 'reflectance.data '((0 0 0.31) (30 180 0.28)))
    (kee:create.unit 'pgcswr.10 'veg nil 'technique.selection.rules)
    (kee:put.value 'pgcswr.10 'kee:external.form
                   '(if (the current.sample.wavelengths
                         of estimate.hemispherical.reflectance
                         is ?x)
                        (lisp (consp (get.value ?x 'reflectance.data)))
                        then
                        (lisp (add.value ?x 'techniques
                                         'pgc.near.nadir))))
    (kee:create.unit 'pgc.followup 'veg nil 'technique.selection.rules)
    (kee:put.value 'pgc.followup 'kee:external.form
                   '(if (the current.sample.wavelengths
                         of estimate.hemispherical.reflectance
                         is ?x)
                        (the techniques of ?x is pgc.near.nadir)
                        then
                        (lisp (add.value ?x 'recommended.techniques
                                         'pgc.near.nadir))))
    (check (kee:unitmsg 'pgcswr.10 'kee:parse))
    (check (kee:unitmsg 'pgc.followup 'kee:parse))
    (check (null (kee:get.value 'pgcswr.10 'kee:parse.errors)))
    (check (equal (sort (names (kee:forward.chain 'technique.selection.rules))
                        #'string<
                        :key #'symbol-name)
                  '(pgc.followup pgcswr.10)))
    (check (kee:trace.events :kind :rule-fire :rule 'pgcswr.10))
    (let* ((fire (first (kee:trace.events :kind :rule-fire
                                          :rule 'pgcswr.10)))
           (match (first (kee:trace.events :kind :rule-match
                                           :rule 'pgcswr.10))))
      (check (numberp (getf fire :activation-id)))
      (check (numberp (getf fire :fire-id)))
      (check (= (getf fire :activation-id)
                (getf match :activation-id))))
    (let ((xref (kee:rule.references 'pgcswr.10)))
      (check (eq (getf xref :kind) :if))
      (check (member 'reflectance.data (getf xref :reads)
                     :key (lambda (reference)
                            (getf reference :slot))))
      (check (member 'techniques (getf xref :writes)
                     :key (lambda (reference)
                            (getf reference :slot))))
      (check (member 'pgcswr.10 (mapcar (lambda (reference)
                                           (getf reference :rule))
                                         (kee:rule.reference.index
                                          :kb 'veg)))))
    (check (equal (kee:get.values wave 'techniques)
                  '(pgc.near.nadir)))
    (check (equal (kee:get.values wave 'recommended.techniques)
                  '(pgc.near.nadir)))
    (kee:forward.chain 'technique.selection.rules)
    (check (equal (kee:get.values wave 'techniques)
                  '(pgc.near.nadir)))
    (check (equal (kee:get.values wave 'recommended.techniques)
                  '(pgc.near.nadir))))
  (kee:create.unit 'people 'veg 'entities 'classes)
  (kee:create.slot 'people 'sport 'member nil nil nil nil
                   '((kee:value.class (kee:one.of golf basketball sailing))
                     (kee:min.cardinality 1)
                     (kee:max.cardinality 1)))
  (kee:create.slot 'people 'phobia 'member nil nil nil nil
                   '((kee:value.class (kee:one.of cats heights close.spaces))
                     (kee:min.cardinality 1)
                     (kee:max.cardinality 1)))
  (kee:create.unit 'tom 'veg nil 'people)
  (check (equal (kee:slot.facet.values 'tom 'sport 'kee:value.class)
                '((kee:one.of golf basketball sailing))))
  (check (signals-error-p
          (lambda ()
            (kee:put.value 'tom 'sport 'tennis))))
  (kee:create.unit 'constraint.rules 'veg 'entities 'classes)
  (check (equal (kee:list.kbs) '(veg)))
  (check (member 'tom (names (kee:list.units 'veg))))
  (kee:create.kb 'delivery)
  (kee:create.unit 'classes 'delivery nil nil)
  (kee:create.unit 'entities 'delivery nil nil)
  (kee:create.unit 'targets 'delivery 'entities 'classes)
  (kee:create.slot 'targets 'status 'member '(pending)
                   nil nil nil '((kee:value.class
                                  (kee:one.of pending ready done))))
  (let ((target (kee:create.unit 'target.a 'delivery nil 'targets)))
    (kee:put.value target 'status 'ready)
    (kee:create.unit 'dashboard 'delivery nil nil)
    (kee:add.value 'dashboard 'primary.target target)
    (kee:create.active.image 'target.status.image target 'status
                             :widget :value
                             :label "Target status"
                             :choices '(pending ready done)
                             :writable-p t)
    (kee:create.kee.picture 'delivery.panel
                            :kb 'delivery
                            :label "Delivery Panel"
                            :width 220
                            :height 100)
    (kee:create.picture.item 'delivery.panel 'delivery.00.title :text
                             :x 12
                             :y 24
                             :text "Delivery KB")
    (kee:create.picture.item 'delivery.panel 'delivery.10.status :active-image
                             :active-image 'target.status.image
                             :x 12
                             :y 38
                             :width 140
                             :height 42)
    (kee:create.picture.viewport 'delivery.viewport 'delivery.panel
                                 :label "Delivery View")
    (kee:create.picture.windowpane 'delivery.window 'delivery.viewport
                                   :label "Delivery Window"
                                   :open-p nil)
    (kee:create.kee.panel 'delivery.image.panel
                          :kind :status
                          :label "Delivery Image Panel"
                          :message "Delivery status"
                          :picture 'delivery.panel
                          :viewport 'delivery.viewport
                          :windowpane 'delivery.window
                          :open-p nil)
    (let ((snapshot (kee:dump.kb 'delivery)))
      (check (eq (getf snapshot :format) :reconstructed-kee-kb))
      (check (eq (getf snapshot :kb) 'delivery))
      (let ((dump-text (with-output-to-string (stream)
                         (kee:write.kb.dump stream 'delivery))))
        (check (search ":KEE-DUMP-UNIT-REF" dump-text))
        (check (eq (getf (kee:read.kb.dump
                          (make-string-input-stream dump-text))
                         :kb)
                   'delivery)))
      (check (signals-error-p
              (lambda ()
                (kee:load.kb.dump snapshot))))
      (kee:load.kb.dump snapshot :replace t)
      (check (eq (kee:kb.name (kee:kb 'delivery)) 'delivery))
      (check (equal (names (kee:unit.parents 'target.a 'member))
                    '(targets)))
      (check (eq (kee:get.value 'target.a 'status) 'ready))
      (check (equal (kee:slot.facet.values 'target.a 'status
                                           'kee:value.class)
                    '((kee:one.of pending ready done))))
      (check (eq (kee:unit.name
                  (kee:get.value 'dashboard 'primary.target))
                 'target.a))
      (check (equal (names (kee:list.active.images 'delivery))
                    '(target.status.image)))
      (check (search "READY"
                     (kee:active.image.html 'target.status.image)))
      (check (equal (names (kee:list.kee.pictures 'delivery))
                    '(delivery.panel)))
      (check (equal (names (kee:picture.viewports 'delivery.panel))
                    '(delivery.viewport)))
      (check (equal (names (kee:picture.windowpanes 'delivery.viewport))
                    '(delivery.window)))
      (check (equal (names (kee:list.kee.panels 'delivery))
                    '(delivery.image.panel)))
      (kee:open.panel 'delivery.image.panel)
      (check (kee:panel.open.p 'delivery.image.panel))
      (check (kee:get.value 'delivery.window 'kee::open.p))
      (check (search "Delivery KB"
                     (kee:kee.picture.svg 'delivery.panel)))))
  (let ((dump-path #p"/private/tmp/kee-delivery-test.dump"))
    (kee:write.kb.dump.file dump-path 'delivery)
    (check (probe-file dump-path))
    (check (eq (getf (kee:read.kb.dump.file dump-path) :kb) 'delivery))
    (check (signals-error-p
            (lambda ()
              (kee:load.kb.dump.file dump-path))))
    (kee:load.kb.dump.file dump-path :replace t)
    (check (eq (kee:get.value 'target.a 'status) 'ready))
    (check (equal (names (kee:list.kee.panels 'delivery))
                  '(delivery.image.panel)))
    (kee:open.panel 'delivery.image.panel)
    (check (kee:panel.open.p 'delivery.image.panel)))
  (kee:goto.kb 'veg)
  (let ((tom-report (kee:inspect.unit 'tom))
        (sport-report (kee:inspect.slot 'tom 'sport))
        (browser-text (with-output-to-string (stream)
                        (kee:print.browser :stream stream
                                           :units '(tom)
                                           :worlds nil))))
    (check (eq (getf tom-report :name) 'tom))
    (check (member 'people (getf tom-report :member-parents)))
    (check (equal (getf sport-report :facets)
                  '((kee:max.cardinality 1)
                    (kee:min.cardinality 1)
                    (kee:value.class
                     (kee:one.of golf basketball sailing)))))
    (check (search "TOM" browser-text))
    (check (search "SPORT" browser-text)))
  (let ((command-text
          (with-output-to-string (stream)
            (check (eq (kee:browser.command '(help) :stream stream)
                       :continue))
            (check (eq (kee:browser.command '(kbs) :stream stream)
                       :continue))
            (check (eq (kee:browser.command '(units veg) :stream stream)
                       :continue))
            (check (eq (kee:browser.command '(unit tom) :stream stream)
                       :continue))
            (check (eq (kee:browser.command '(slot tom sport) :stream stream)
                       :continue))
            (check (eq (kee:browser.command '(dump-kb delivery) :stream stream)
                       :continue))
            (check (eq (kee:browser.command
                        '(write-dump "/private/tmp/kee-delivery-browser.dump"
                          delivery)
                        :stream stream)
                       :continue))
            (check (eq (kee:browser.command
                        '(load-dump "/private/tmp/kee-delivery-browser.dump"
                          :replace t)
                        :stream stream)
                       :continue))
            (check (eq (kee:browser.command '(unit-graph veg) :stream stream)
                       :continue))
            (check (eq (kee:browser.command '(viewer 2) :stream stream)
                       :continue))
            (check (eq (kee:browser.command '(current) :stream stream)
                       :continue))
            (check (eq (kee:browser.command '(quit) :stream stream)
                       :quit)))))
    (check (search "Commands:" command-text))
    (check (search "Knowledge Bases" command-text))
    (check (search "Units in VEG" command-text))
    (check (search "TOM" command-text))
    (check (search "SPORT" command-text))
    (check (search ":RECONSTRUCTED-KEE-KB" command-text))
    (check (search "Wrote KB dump" command-text))
    (check (search "Loaded KB dump: DELIVERY" command-text))
    (check (search "digraph" command-text))
    (check (search "<!doctype html>" command-text))
    (check (search "member" command-text))
    (check (search "Leaving KEE browser" command-text)))
  (kee:goto.kb 'veg)
  (let* ((unit-graph (kee:unit.graph :kb 'veg))
         (unit-dot (kee:unit.graph.dot :kb 'veg))
         (viewer-html (kee:kee.viewer.html :kb 'veg :world-limit 0)))
    (check (member "unit:VEG/TOM" (getf unit-graph :nodes)
                   :test #'string=
                   :key (lambda (node) (getf node :id))))
    (check (member 'member (getf unit-graph :edges)
                   :key (lambda (edge) (getf edge :relation))))
    (check (search "digraph" unit-dot))
    (check (search "unit:VEG/TOM" unit-dot))
    (check (search "id='kee-data'" viewer-html))
    (check (search "unit:VEG/TOM" viewer-html))
    (check (search "function render" viewer-html))
    (check (search "\"initial\"" viewer-html))
    (check (search "\"session\"" viewer-html))
    (check (search "const INITIAL" viewer-html))
    (check (search "INITIAL.view" viewer-html))
    (check (search "\"kbs\"" viewer-html))
    (check (search "\"details\"" viewer-html))
    (check (search "\"activeImages\"" viewer-html))
    (check (search "\"pictures\"" viewer-html))
    (check (search "\"panels\"" viewer-html))
    (check (search "\"ruleReferences\"" viewer-html))
    (check (search "\"ruleReference\"" viewer-html))
    (check (search "\"traces\"" viewer-html))
    (check (search "\"agendaId\"" viewer-html))
    (check (search "\"activationId\"" viewer-html))
    (check (search "\"fireId\"" viewer-html))
    (check (search "TEMPERATURE.GAUGE" viewer-html))
    (check (search "RULE-FIRE" viewer-html))
    (check (search "METHOD-CALL" viewer-html))
    (check (search "\"methodKind\"" viewer-html))
    (check (search "Method dispatch" viewer-html))
    (check (search "ADD.VALUE" viewer-html))
    (check (search "CURRENT.SAMPLE.WAVELENGTHS" viewer-html))
    (check (search "\"facets\"" viewer-html))
    (check (search "MAX.CARDINALITY" viewer-html))
    (check (search "id='current-kb'" viewer-html))
    (check (search "id='hierarchy-browser'" viewer-html))
    (check (search "id='slot-browser'" viewer-html))
    (check (search "id='review-tour'" viewer-html))
    (check (search "Review Tour" viewer-html))
    (check (search "data-review-tour" viewer-html))
    (check (search "['worlds', 'Worlds']" viewer-html))
    (check (search "['kee-pictures', 'KEEpictures']" viewer-html))
    (check (search "['panels', 'Panels']" viewer-html))
    (check (search "selectReviewTour" viewer-html))
    (check (search "reviewTourTarget" viewer-html))
    (check (search "id='desktop-roster'" viewer-html))
    (check (search "renderDesktopRoster" viewer-html))
    (check (search "Lisp Listener" viewer-html))
    (check (search "KEEpictures" viewer-html))
    (check (search "id='session-pane'" viewer-html))
    (check (search "renderSessionPane" viewer-html))
    (check (search "data-session-window" viewer-html))
    (check (search "id='picture-browser'" viewer-html))
    (check (search "renderPictureBrowser" viewer-html))
    (check (search "pictureViewportSummary" viewer-html))
    (check (search "data-picture-name" viewer-html))
    (check (search "renderPanelBrowser" viewer-html))
    (check (search "data-panel-name" viewer-html))
    (check (search "Sensor Image Panel" viewer-html))
    (check (search "Sensor Panel" viewer-html))
    (check (search "TEMPERATURE.CARD" viewer-html))
    (check (search "Sensor View" viewer-html))
    (check (search "Sensor Window" viewer-html))
    (check (search "\"kind\":\"PICTURE-MOUSE\"" viewer-html))
    (check (search "\"kind\":\"PANEL-OPEN\"" viewer-html))
    (check (search "\"panel\":\"SENSOR.IMAGE.PANEL\"" viewer-html))
    (check (search "\"picture\":\"SENSOR.PANEL\"" viewer-html))
    (check (search "\"windowpane\":\"SENSOR.WINDOW\"" viewer-html))
    (check (search "Picture mouse" viewer-html))
    (check (search "Panel opened" viewer-html))
    (check (search "pictures" viewer-html))
    (check (search "Top Level Units" viewer-html))
    (check (search "Slot Table" viewer-html))
    (check (search "slotFacetText" viewer-html))
    (check (search "renderSlotTableRow" viewer-html))
    (check (search "<th>Local</th><th>Inherited</th><th>Combined</th><th>Facets</th>"
                   viewer-html))
    (check (search "ActiveImages" viewer-html))
    (check (search "Trace" viewer-html))
    (check (search "Rule Xref" viewer-html))
    (check (search "data-xref-control" viewer-html))
    (check (search "variable targets" viewer-html))
    (check (search "xrefVariableTargetP" viewer-html))
    (check (search "renderActiveImage" viewer-html))
    (check (search "renderRuleXref" viewer-html))
    (check (search "renderTracePane" viewer-html))
    (check (search "renderTraceGraph" viewer-html))
    (check (search "data-trace-control" viewer-html))
    (check (search "data-trace-control='family'" viewer-html))
    (check (search "traceFamily" viewer-html))
    (check (search "all families" viewer-html))
    (check (search "data-trace-search" viewer-html))
    (check (search "data-trace-jump" viewer-html))
    (check (search "traceMatchesQuery" viewer-html))
    (check (search "jumpTrace" viewer-html))
    (check (search "traceDetailHtml" viewer-html))
    (check (search "Focused Trace" viewer-html))
    (check (search "data-trace-id" viewer-html))
    (check (search "focusedTraceReferenceIds" viewer-html))
    (check (search "trace-hit" viewer-html))
    (check (search "traceTargets" viewer-html))
    (check (search "traceTargetButtons" viewer-html))
    (check (search "selected node" viewer-html))
    (check (search "trace-graph" viewer-html))
    (check (search "traceRef" viewer-html))
    (check (search "agenda-board" viewer-html))
    (check (search "renderAgendaPane" viewer-html))
    (check (search "agendaGroups" viewer-html))
    (check (search "data-agenda-jump" viewer-html))
    (check (search "agendaJumpRows" viewer-html))
    (check (search "jumpAgenda" viewer-html))
    (check (search "Next Fired" viewer-html))
    (check (search "agenda-drilldown" viewer-html))
    (check (search "renderAgendaDrilldown" viewer-html))
    (check (search "agendaCandidateAction" viewer-html))
    (check (search "agendaEffectEvents" viewer-html))
    (check (search "renderAgendaEffects" viewer-html))
    (check (search "world-slot-write" viewer-html))
    (check (search "Conflict Set" viewer-html))
    (check (search "causality-graph" viewer-html))
    (check (search "causal-node" viewer-html))
    (check (search "renderCausalityGraph" viewer-html))
    (check (search "renderCausalityFlow" viewer-html))
    (check (search "causalEffectLabel" viewer-html))
    (check (search "why-trails" viewer-html))
    (check (search "provenanceTrail" viewer-html))
    (check (search "whyTrailTargets" viewer-html))
    (check (search "renderWorldWhyTrails" viewer-html))
    (check (search "renderFocusedTraceWhy" viewer-html))
    (check (search "assumption-trails" viewer-html))
    (check (search "worldAssumptionNames" viewer-html))
    (check (search "renderWorldAssumptions" viewer-html))
    (check (search "branchWriteTrace" viewer-html))
    (check (search "worldAssumptionsFromRecords" viewer-html))
    (check (search "assumptionRecordEvent" viewer-html))
    (check (search "renderFactLabels" viewer-html))
    (check (search "factLabelSummary" viewer-html))
    (check (search "trace-map" viewer-html))
    (check (search "renderTraceMap" viewer-html))
    (check (search "traceMapLane" viewer-html))
    (check (search "trace-map-link.focused" viewer-html))
    (check (search "trace-map-link.branch" viewer-html))
    (check (search "focusedTraceWorldPathNames" viewer-html))
    (check (search "traceTouchesWorldPath" viewer-html))
    (check (search "data-trace-map-play" viewer-html))
    (check (search "data-trace-map-speed" viewer-html))
    (check (search "data-trace-map-loop" viewer-html))
    (check (search "stepTraceMap" viewer-html))
    (check (search "traceReplayDelay" viewer-html))
    (check (search "traceMapPosition" viewer-html))
    (check (search "toggleTraceReplay" viewer-html))
    (check (search "setActiveImageLocal" viewer-html))
    (check (search "data-active-image-name" viewer-html))
    (check (search "activeBrowserUnitP" viewer-html))
    (check (search "renderHierarchyBrowser" viewer-html))
    (check (search "renderUnitDetail" viewer-html))
    (check (search "id='node-list'" viewer-html))
    (check (search "renderNodeBrowser" viewer-html))
    (check (search "selectReference" viewer-html))
    (check (search "data-ref-kind" viewer-html)))
  (let ((initial-html
          (kee:kee.viewer.html :kb 'veg
                               :world-limit 0
                               :initial-view "worlds"
                               :initial-selection "world:TOM-GOLF-HEIGHTS"
                               :initial-trace-scope "selected"
                               :session '(:listener ("CL-USER> (SETUP)")
                                          :typescript ("Typescript sample")
                                          :prompt ("Prompt sample")))))
    (check (search "\"view\":\"worlds\"" initial-html))
    (check (search "\"selected\":\"world:TOM-GOLF-HEIGHTS\"" initial-html))
    (check (search "\"traceScope\":\"selected\"" initial-html))
    (check (search "\"listener\":[\"CL-USER\\u003E (SETUP)\"]" initial-html))
    (check (search "\"typescript\":[\"Typescript sample\"]" initial-html))
    (check (search "\"prompt\":[\"Prompt sample\"]" initial-html)))
  (let ((loop-text
          (with-output-to-string (output)
            (with-input-from-string (input "(kbs) (quit)")
              (check (eq (kee:browse :input input :output output)
                         :quit))))))
    (check (search "KEE browser" loop-text))
    (check (search "Knowledge Bases" loop-text)))
  (kee:create.unit 'heights.golf 'veg nil 'constraint.rules)
  (kee:put.value 'heights.golf 'kee:external.form
                 '(while (the sport of ?person is golf)
                         (the phobia of ?person is heights)
                    believe false))
  (check (kee:parse 'heights.golf))
  (let ((bad-world (kee:create.world 'tom-golf-heights))
        (good-world (kee:create.world 'tom-golf-cats)))
    (kee:with-world (bad-world)
      (kee:put.value 'tom 'sport 'golf)
      (kee:put.value 'tom 'phobia 'heights)
      (kee:forward.chain 'constraint.rules)
      (check (kee:world.inconsistent.p bad-world))
      (check (kee:trace.events :kind :contradiction
                               :world 'tom-golf-heights))
      (let ((reasons (kee:why.false bad-world)))
        (check (= (length reasons) 1))
        (check (eq (kee:justification.rule (first reasons)) 'heights.golf))
        (check (equal (cdr (assoc "?PERSON"
                                  (kee:justification.bindings (first reasons))
                                  :test #'string=))
                      'tom))
        (check (equal (kee:justification.proposition (first reasons))
                      'false))))
    (kee:with-world (good-world)
      (kee:put.value 'tom 'sport 'golf)
      (kee:put.value 'tom 'phobia 'cats)
      (kee:forward.chain 'constraint.rules)
      (check (not (kee:world.inconsistent.p good-world))))
    (let ((bad-report (kee:inspect.world bad-world))
          (browser-text (with-output-to-string (stream)
                          (kee:print.browser :stream stream
                                             :units '(tom)
                                             :worlds (kee:inspect.world.tree)))))
      (check (eq (getf bad-report :name) 'tom-golf-heights))
      (check (getf bad-report :inconsistent-p))
      (check (= (length (getf bad-report :nogoods)) 1))
      (check (search "TOM-GOLF-HEIGHTS" browser-text))
      (check (search "HEIGHTS.GOLF" browser-text)))
    (let ((viewer-html (kee:kee.viewer.html :kb 'veg
                                            :worlds (list bad-world
                                                          good-world))))
      (check (search "TOM-GOLF-HEIGHTS" viewer-html))
      (check (search "HEIGHTS.GOLF" viewer-html))
      (check (search "\"nogoods\"" viewer-html))
      (check (search "\"conditions\"" viewer-html)))
    (let* ((world-graph (kee:world.graph))
           (world-dot (kee:world.graph.dot)))
      (check (member "world:TOM-GOLF-HEIGHTS" (getf world-graph :nodes)
                     :test #'string=
                     :key (lambda (node) (getf node :id))))
      (check (search "mistyrose" world-dot))
      (check (search "TOM-GOLF-HEIGHTS" world-dot)))
    (check (kee:true.in.world bad-world 'tom 'sport 'golf))
    (check (null (kee:get.value 'tom 'sport))))
  (kee:create.unit 'hypothesis.rules 'veg 'entities 'classes)
  (kee:create.unit 'guess.tom.golf 'veg nil 'hypothesis.rules)
  (kee:put.value 'guess.tom.golf 'kee:external.form
                 '(if (the needs.guess of ?person is sport)
                      (lisp (cant.find ?person 'sport))
                      then
                      (in.new.world
                       (the sport of ?person is values))))
  (check (kee:parse 'guess.tom.golf))
  (let ((root-world (kee:create.world 'root-hypotheses)))
    (kee:with-world (root-world)
      (kee:put.value 'tom 'needs.guess 'sport)
      (kee:forward.chain 'hypothesis.rules)
      (kee:forward.chain 'hypothesis.rules))
    (let ((children (remove-if-not
                     (lambda (world)
                       (eq (kee:world.parent world) root-world))
                     (kee:$worlds))))
      (check (= (length children) 3))
      (check (equal (sort (mapcar (lambda (child)
                                     (kee:with-world (child)
                                       (first (kee:get.values 'tom 'sport))))
                                   children)
                          #'string<
                          :key #'symbol-name)
                    '(basketball golf sailing)))
      (let ((child (find-if (lambda (world)
                              (kee:true.in.world world 'tom 'sport 'golf))
                            children)))
        (check child)
        (check (not (kee:true.in.world root-world 'tom 'sport 'golf)))
        (check (member 'sport (kee:world.facts child)
                       :key (lambda (fact) (getf fact :slot))))
        (let ((environment (kee:world.environment child)))
          (check (= (length environment) 1))
          (check (eq (kee:assumption.world (first environment))
                     (kee:get.world.name child)))
          (check (eq (kee:assumption.parent (first environment))
                     (kee:get.world.name root-world)))
          (check (equal (third (kee:assumption.fact (first environment)))
                        'sport))
          (check (numberp (kee:assumption.fire-id (first environment)))))
        (let ((labels (kee:world.labels child)))
          (check (= (length labels) 1))
          (check (eq (kee:label.kind (first labels)) :fact))
          (check (equal (third (kee:label.fact (first labels))) 'sport))
          (check (= (length (kee:label.environment (first labels))) 1))
          (check (eq (kee:label.rule (first labels)) 'guess.tom.golf))
          (check (numberp (kee:label.fire-id (first labels)))))
        (let ((fire-ids (remove nil
                                (mapcar (lambda (event)
                                          (getf event :fire-id))
                                        (kee:trace.events :kind :rule-fire
                                                          :rule
                                                          'guess.tom.golf)))))
          (check (some (lambda (event)
                         (member (getf event :fire-id) fire-ids))
                       (kee:trace.events :kind :world-branch)))
          (check (some (lambda (event)
                         (member (getf event :fire-id) fire-ids))
                       (kee:trace.events :kind :world-slot-write))))
        (kee:with-world (child)
          (kee:put.value 'tom 'phobia 'heights)
          (kee:forward.chain 'constraint.rules))
        (let* ((nogood (first (kee:world.nogoods child)))
               (report (kee:inspect.world child)))
          (check nogood)
          (check (= (length (kee:nogood.environment nogood)) 1))
          (check (= (length (getf report :environment)) 1))
          (check (= (length (getf report :labels)) 2))
          (check (getf (find 'sport (getf report :facts)
                             :key (lambda (fact) (getf fact :slot)))
                       :labels))
          (check (= (length (getf (first (getf report :nogoods))
                                  :environment))
                    1)))
        (dotimes (index 205)
          (kee:record.trace.event :agenda
                                  :world (intern (format nil "NOISE-~D" index)
                                                 :kee)
                                  :rule-class 'hypothesis.rules))
        (let ((viewer-html (kee:kee.viewer.html :kb 'veg
                                                :worlds (list child))))
          (check (search "\"kind\":\"WORLD-BRANCH\"" viewer-html))
          (check (search "\"kind\":\"WORLD-SLOT-WRITE\"" viewer-html))
          (check (search "\"kind\":\"RULE-MATCH\"" viewer-html))
          (check (search "\"kind\":\"RULE-FIRE\"" viewer-html))
          (check (search "\"rule\":\"GUESS.TOM.GOLF\"" viewer-html))
          (check (search "\"environment\"" viewer-html))
          (check (search "\"labels\"" viewer-html))
          (check (search "\"kind\":\"FACT\"" viewer-html))
          (check (search "world-label-retract" viewer-html))
          (check (search "Label retracted" viewer-html))
          (check (search "\"fact\":[\"VEG\",\"TOM\",\"SPORT\",[\"GOLF\"]]"
                         viewer-html)))
        (kee:with-world (child)
          (kee:put.value 'tom 'sport 'basketball))
        (let ((labels (kee:world.labels child)))
          (check (null (kee:world.environment child)))
          (check (= (length labels) 1))
          (check (equal (fourth (kee:label.fact (first labels)))
                        '(basketball)))
          (check (null (kee:label.environment (first labels)))))
        (check (kee:true.in.world child 'tom 'sport 'basketball))
        (check (not (kee:true.in.world child 'tom 'sport 'golf)))
        (check (kee:trace.events :kind :world-label-retract
                                 :world (kee:get.world.name child))))))
  (kee:create.unit 'label.subject 'veg nil nil)
  (kee:goto.world nil)
  (let ((label-world (kee:create.world 'label-removal-smoke)))
    (kee:with-world (label-world)
      (kee:put.value 'label.subject 'status 'ready)
      (check (= (length (kee:world.labels label-world)) 1))
      (kee:remove.all.values 'label.subject 'status))
    (check (null (kee:world.labels label-world)))
    (check (kee:trace.events :kind :world-label-retract
                             :world 'label-removal-smoke)))
  (format t "~&~A~%" (if (zerop *failures*) "All tests passed." "Tests failed."))
  (unless (zerop *failures*)
    (quit-with-status 1)))

(run)
