(load (merge-pathnames "../src/package.lisp" *load-truename*))
(load (merge-pathnames "../src/core.lisp" *load-truename*))
(load (merge-pathnames "../src/worlds.lisp" *load-truename*))
(load (merge-pathnames "../src/rules.lisp" *load-truename*))
(load (merge-pathnames "../src/inspect.lisp" *load-truename*))
(load (merge-pathnames "../src/browser.lisp" *load-truename*))
(defparameter *run-hamburg-puzzle-demo* nil)
(load (merge-pathnames "hamburg-puzzle-mini.lisp" *load-truename*))

(in-package #:cl-user)

(setup)
(kee:create.world 'hypothesis-root)
(kee:run.world.agenda '(constraint.rules hypothesis.rules) :max-iterations 20)
(kee:browse)
