(defpackage #:kee
  (:use #:cl)
  (:export
   #:reset-kee
   #:create.kb
   #:kb.exists.p
   #:goto.kb
   #:kb
   #:kb.name
   #:create.unit
   #:unit
   #:unit.exists.p
   #:unit.name
   #:unit.kb
   #:rename.unit
   #:delete.unit
   #:unit.parents
   #:unit.children
   #:unit.ancestors
   #:unit.descendant.p
   #:unit.slot.names
   #:create.slot
   #:delete.slot
   #:slot.exists.p
   #:get.value
   #:get.values
   #:put.value
   #:put.values
   #:add.value
   #:add.values
   #:remove.all.values
   #:put.facet.value
   #:remove.all.facet.values
   #:add.method
   #:active.values
   #:active-values
   #:value-read
   #:value-written
   #:value-added
   #:values-removed
   #:create.world
   #:world
   #:goto.world
   #:current.world
   #:get.world.name
   #:world.inconsistent.p
   #:world.parent
   #:$worlds
   #:with-world
   #:in.new.world
   #:true.in.world
   #:believe
   #:false
   #:parse
   #:external.form
   #:internal.form
   #:parse.errors
   #:forward.chain
   #:unitmsg
   #:unitmsg*))
