(defpackage #:kee
  (:use #:cl)
  (:export
   #:reset-kee
   #:create.kb
   #:kb.exists.p
   #:goto.kb
   #:kb
   #:kb.name
   #:create.unit
   #:unit
   #:unit.exists.p
   #:unit.name
   #:unit.kb
   #:rename.unit
   #:delete.unit
   #:unit.parents
   #:unit.children
   #:unit.ancestors
   #:unit.descendant.p
   #:unit.slot.names
   #:create.slot
   #:delete.slot
   #:slot.exists.p
   #:get.value
   #:get.values
   #:put.value
   #:put.values
   #:add.value
   #:add.values
   #:remove.all.values
   #:put.facet.value
   #:remove.all.facet.values
   #:slot.facet.values
   #:value.class
   #:value-class
   #:one.of
   #:min.cardinality
   #:min-cardinality
   #:max.cardinality
   #:max-cardinality
   #:slot.allowed.values
   #:add.method
   #:active.values
   #:active-values
   #:value-read
   #:value-written
   #:value-added
   #:values-removed
   #:create.world
   #:world
   #:goto.world
   #:current.world
   #:get.world.name
   #:world.inconsistent.p
   #:world.parent
   #:world.facts
   #:world.justifications
   #:world.nogoods
   #:$worlds
   #:with-world
   #:in.new.world
   #:true.in.world
   #:believe
   #:false
   #:why.false
   #:consistent.worlds
   #:justification.rule
   #:justification.bindings
   #:justification.conditions
   #:justification.action
   #:justification.proposition
   #:nogood.world
   #:nogood.justification
   #:parse
   #:external.form
   #:internal.form
   #:parse.errors
   #:forward.chain
   #:run.world.agenda
   #:cant.find
   #:find.any
   #:list.kbs
   #:list.units
   #:inspect.unit
   #:inspect.slot
   #:inspect.world
   #:inspect.world.tree
   #:print.browser
   #:unit.graph
   #:world.graph
   #:unit.graph.dot
   #:world.graph.dot
   #:write.unit.graph.dot
   #:write.world.graph.dot
   #:browser.commands
   #:browser.command
   #:browse
   #:unitmsg
   #:unitmsg*))
